# Generated by Django 4.2.16 on 2024-10-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_nutrition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
