# Generated by Django 5.1.1 on 2024-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body_part', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
