# Generated by Django 5.1.1 on 2024-09-22 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(to='workouts.exercise')),
            ],
        ),
    ]
