# Generated by Django 5.1.1 on 2024-09-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_recommendedexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedexercise',
            name='recommended_date',
        ),
        migrations.AddField(
            model_name='recommendedexercise',
            name='muscle_group',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
