# Generated by Django 4.2.16 on 2024-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routineplanner', '0002_routine_remove_note_workout_remove_workout_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routine_images/'),
        ),
    ]
